export const players = [
    {
        id: 1,
        name: 'Cristiano Ronaldo',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'Portugal',
        club: 'Manchester United',
    },
    {
        id: 2,
        name: 'Lionel Messi',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'Argentina',
        club: 'Paris Saint-Germain',
    },
    {
        id: 3,
        name: 'Neymar Jr',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'Brazil',
        club: 'Paris Saint-Germain',
    },
    {
        id: 4,
        name: 'Robert Lewandowski',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'Poland',
        club: 'Bayern Munich',
    },
    {
        id: 5,
        name: 'Kylian Mbappe',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'France',
        club: 'Paris Saint-Germain',
    },
    {
        id: 6,
        name: 'Kevin De Bruyne',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'Belgium',
        club: 'Manchester City',
    },
    {
        id: 7,
        name: 'Mohamed Salah',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'Egypt',
        club: 'Liverpool',
    },
    {
        id: 8,
        name: 'Sadio Mane',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'Senegal',
        club: 'Liverpool',
    },
    {
        id: 9,
        name: 'Luka Modric',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'Croatia',
        club: 'Real Madrid',
    },
    {
        id: 10,
        name: 'Virgil van Dijk',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'Netherlands',
        club: 'Liverpool',
    },
    {
        id: 11,
        name: 'Sergio Ramos',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'Spain',
        club: 'Paris Saint-Germain',
    },
    {
        id: 12,
        name: 'Eden Hazard',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'Belgium',
        club: 'Real Madrid',
    },
    {
        id: 13,
        name: 'Raheem Sterling',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'England',
        club: 'Manchester City',
    },
    {
        id: 14,
        name: 'Paul Pogba',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'France',
        club: 'Manchester United',
    },
    {
        id: 15,
        name: 'Harry Kane',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'England',
        club: 'Tottenham Hotspur',
    },
    {
        id: 16,
        name: 'Antoine Griezmann',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'France',
        club: 'Barcelona',
    },
    {
        id: 17,
        name: 'Gareth Bale',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'Wales',
        club: 'Real Madrid',
    },
    {
        id: 18,
        name: 'Bruno Fernandes',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'Portugal',
        club: 'Manchester United',
    },
    {
        id: 19,
        name: 'Trent Alexander-Arnold',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'England',
        club: 'Liverpool',
    },
    {
        id: 20,
        name: 'Marc-André ter Stegen',
        photoUrl: 'https://via.placeholder.com/150',
        country: 'Germany',
        club: 'Barcelona',
    },
];
